### ISSUE TITLE
vscale_ctrl_constants.vh needed by vscale_core.v

### ISSUE THREAD

**Issue by LGTMCU** [ucb-bar/vscale#1]

**Comment by albert-magyar** [comment]
This file is in the repository. Are you trying to use the VCS Makefile targets?

**Comment by LGTMCU** [comment]
I can find this .vh file in repository, but It seems we must include it explicity in .v file
when try to view/sim the project with verdi/vcs...

Thanks,

**Comment by olofk** [comment]
Same thing with modelsim (but Icarus seems to work without an explicit include). I've added this patch https://github.com/openrisc/orpsoc-cores/blob/master/cores/vscale/files/0002-Fix-missing-includes.patch to make it work with modelsim under FuseSoC

**Comment by albert-magyar** [comment]
Thanks for following up. I added the includes from your patch, so I'll mark this closed for now.
